name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")
college = input("Enter your college name: ")
course = input("Enter your course: ")
year = int(input("Enter your year of study: "))
print()
print("---------------------------")
print("     PERSONAL PROFILE")
print("---------------------------")
print(f"Name      : {name}")
print(f"Age       : {age}")
print(f"City      : {city}")
print(f"College   : {college}")
print(f"Course    : {course}")
print(f"Year      : {year}")
print("---------------------------")